import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Lock, CreditCard } from 'lucide-react'
import { useCart } from '@/contexts/CartContext'
import { supabase } from '@/lib/supabase'
import { formatPrice } from '@/lib/utils'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'

export default function Checkout() {
  const navigate = useNavigate()
  const { items, total, discount, subtotal, currency, coupon, clearCart } = useCart()
  const [form, setForm] = useState({ name: '', email: '', phone: '' })
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  if (items.length === 0) {
    navigate('/cart')
    return null
  }

  async function handleCheckout() {
    if (!form.email || !form.name) {
      setError('Please fill in your name and email')
      return
    }
    setLoading(true)
    setError('')

    try {
      // 1. Create or get customer
      const { data: existingCustomer } = await supabase
        .from('bybisa_customers')
        .select('id')
        .eq('email', form.email.toLowerCase())
        .single()

      let customerId: string
      if (existingCustomer) {
        customerId = existingCustomer.id
      } else {
        const { data: newCustomer, error: custErr } = await supabase
          .from('bybisa_customers')
          .insert({ email: form.email.toLowerCase(), name: form.name, phone: form.phone || null })
          .select('id')
          .single()
        if (custErr) throw custErr
        customerId = newCustomer!.id
      }

      // 2. Create purchases for each item
      const purchases = []
      for (const item of items) {
        const { data: purchase, error: purchErr } = await supabase
          .from('bybisa_purchases')
          .insert({
            customer_id: customerId,
            product_id: item.product.id,
            order_number: '', // Auto-generated by trigger
            amount: item.product.price,
            currency: item.product.currency,
            status: 'pending',
          })
          .select('*')
          .single()
        if (purchErr) throw purchErr
        purchases.push(purchase!)
      }

      // 3. Track analytics
      for (const item of items) {
        await supabase.from('bybisa_analytics').insert({
          event_type: 'purchase',
          product_id: item.product.id,
          customer_id: customerId,
          metadata: { amount: item.product.price, currency: item.product.currency },
        })
      }

      // 4. Update coupon usage if applicable
      if (coupon) {
        await supabase
          .from('bybisa_coupons')
          .update({ uses_count: coupon.uses_count + 1 })
          .eq('id', coupon.id)
      }

      // 5. Initiate PesaPal payment via serverless API (keeps consumer secret server-side)
      const merchantRef = purchases[0].order_number

      const apiRes = await fetch('/api/pesapal/create-order', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: merchantRef,
          currency: currency,
          amount: total,
          description: items.map(i => i.product.title).join(', '),
          billing_address: {
            email_address: form.email,
            phone_number: form.phone || undefined,
            first_name: form.name.split(' ')[0],
            last_name: form.name.split(' ').slice(1).join(' ') || undefined,
          },
        }),
      })

      if (!apiRes.ok) {
        const errData = await apiRes.json().catch(() => ({ error: 'Unknown error' }))
        throw new Error(errData.error || `Payment API error (${apiRes.status})`)
      }

      const { redirect_url } = await apiRes.json()

      if (!redirect_url) {
        throw new Error('No redirect URL returned from payment gateway')
      }

      // Redirect customer to PesaPal hosted payment page
      window.location.href = redirect_url

    } catch (err: any) {
      console.error('Checkout error:', err)
      setError(err.message || 'An error occurred. Please try again.')
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-[#F9F9F9] py-12">
      <div className="max-w-2xl mx-auto px-4">
        <h1 className="text-3xl font-bold text-[#121212] mb-8">Checkout</h1>

        {/* Customer form */}
        <div className="bg-white rounded-2xl p-6 mb-6 shadow-sm">
          <h2 className="text-lg font-semibold text-[#121212] mb-4">Your Information</h2>
          <div className="space-y-4">
            <Input
              label="Full Name"
              value={form.name}
              onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
              placeholder="Esther Nakamya"
              required
            />
            <Input
              label="Email Address"
              type="email"
              value={form.email}
              onChange={e => setForm(f => ({ ...f, email: e.target.value }))}
              placeholder="esther@example.com"
              helperText="Download links will be sent to this email"
              required
            />
            <Input
              label="Phone Number (optional)"
              type="tel"
              value={form.phone}
              onChange={e => setForm(f => ({ ...f, phone: e.target.value }))}
              placeholder="+256 700 000 000"
              helperText="For MTN MoMo or Airtel Money payments"
            />
          </div>
        </div>

        {/* Order summary */}
        <div className="bg-white rounded-2xl p-6 mb-6 shadow-sm">
          <h2 className="text-lg font-semibold text-[#121212] mb-4">Order Summary</h2>
          <div className="space-y-3">
            {items.map(item => (
              <div key={item.product.id} className="flex justify-between items-center">
                <span className="text-sm text-[#121212]">{item.product.title}</span>
                <span className="text-sm font-medium text-[#121212]">{formatPrice(item.product.price, item.product.currency)}</span>
              </div>
            ))}
          </div>
          <div className="border-t border-gray-100 mt-4 pt-4 space-y-2">
            <div className="flex justify-between text-sm text-gray-500">
              <span>Subtotal</span>
              <span>{formatPrice(subtotal, currency)}</span>
            </div>
            {discount > 0 && (
              <div className="flex justify-between text-sm text-green-600">
                <span>Discount ({coupon?.code})</span>
                <span>-{formatPrice(discount, currency)}</span>
              </div>
            )}
            <div className="flex justify-between text-base font-bold text-[#121212]">
              <span>Total</span>
              <span>{formatPrice(total, currency)}</span>
            </div>
          </div>
        </div>

        {error && (
          <div className="bg-red-50 border border-red-200 rounded-xl p-4 mb-4 text-sm text-red-700">
            {error}
          </div>
        )}

        <Button
          onClick={handleCheckout}
          loading={loading}
          disabled={loading}
          className="w-full"
          size="lg"
        >
          <Lock className="w-4 h-4 mr-2" />
          <CreditCard className="w-4 h-4 mr-2" />
          {loading ? 'Redirecting to payment...' : `Pay ${formatPrice(total, currency)} via PesaPal`}
        </Button>

        <p className="text-xs text-gray-400 text-center mt-3">
          Secured by PesaPal Â· Card, MTN MoMo, Airtel Money accepted
        </p>
      </div>
    </div>
  )
}
