import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { Lock, CreditCard } from 'lucide-react'
import { useCart } from '@/contexts/CartContext'
import { supabase } from '@/lib/supabase'
import { formatPrice, getProductPrice } from '@/lib/utils'
import { getAuthToken, registerIPN, submitOrder } from '@/lib/pesapal'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'

export default function Checkout() {
  const navigate = useNavigate()
  const {
    items,
    total,
    discount,
    subtotal,
    currency,
    selectedCurrency,
    setSelectedCurrency,
    coupon,
    clearCart,
  } = useCart()
  const [form, setForm] = useState({ name: '', email: '', phone: '' })
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    if (items.length === 0) {
      navigate('/cart')
    }
  }, [items, navigate])

  if (items.length === 0) {
    return null
  }

  async function handleCheckout() {
    if (!form.email || !form.name) {
      setError('Please fill in your name and email')
      return
    }
    setLoading(true)
    setError('')

    try {
      // 1. Create or get customer
      const { data: existingCustomer } = await supabase
        .from('bybisa_customers')
        .select('id')
        .eq('email', form.email.toLowerCase())
        .single()

      let customerId: string
      if (existingCustomer) {
        customerId = existingCustomer.id
      } else {
        const { data: newCustomer, error: custErr } = await supabase
          .from('bybisa_customers')
          .insert({ email: form.email.toLowerCase(), name: form.name, phone: form.phone || null })
          .select('id')
          .single()
        if (custErr) throw custErr
        customerId = newCustomer!.id
      }

      // 2. Create purchases for each item
      const purchases: any[] = []
      for (const item of items) {
        const itemPrice = getProductPrice(item.product, selectedCurrency)
        const { data: purchase, error: purchErr } = await supabase
          .from('bybisa_purchases')
          .insert({
            customer_id: customerId,
            product_id: item.product.id,
            order_number: '', // Auto-generated by trigger
            amount: itemPrice,
            currency: selectedCurrency,
            status: 'pending',
          })
          .select('*')
          .single()
        if (purchErr) throw purchErr
        purchases.push(purchase)
      }

      // 3. Track analytics
      for (const item of items) {
        await supabase.from('bybisa_analytics').insert({
          event_type: 'purchase',
          product_id: item.product.id,
          customer_id: customerId,
          metadata: { amount: getProductPrice(item.product, selectedCurrency), currency: selectedCurrency },
        })
      }

      // 4. Update coupon usage if applicable
      if (coupon) {
        await supabase
          .from('bybisa_coupons')
          .update({ uses_count: coupon.uses_count + 1 })
          .eq('id', coupon.id)
      }

      // 5. Initiate PesaPal payment with selected currency
      try {
        const token = await getAuthToken()
        const ipnId = await registerIPN(token)
        const merchantRef = purchases[0].order_number

        const redirectUrl = await submitOrder(token, {
          id: merchantRef,
          currency: selectedCurrency,  // Dynamic: 'USD' or 'UGX'
          amount: total,
          description: items.map(i => i.product.title).join(', '),
          callback_url: `${window.location.origin}/payment-callback?ref=${merchantRef}`,
          notification_id: ipnId,
          billing_address: {
            email_address: form.email,
            phone_number: form.phone || undefined,
            first_name: form.name.split(' ')[0],
            last_name: form.name.split(' ').slice(1).join(' ') || undefined,
          },
        })

        // Redirect to PesaPal
        window.location.href = redirectUrl
      } catch (payErr) {
        console.error('PesaPal error:', payErr)

        navigate(`/payment-callback?ref=${purchases[0].order_number}&pending=true`)
      }
    } catch (err: any) {
      setError(err.message || 'An error occurred. Please try again.')
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-surface py-10 px-4">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-2xl font-bold text-text mb-8">Checkout</h1>

        <div className="grid md:grid-cols-2 gap-8">
          {/* Customer form */}
          <div>
            <div className="bg-white rounded-2xl p-6 border border-border">
              <h3 className="font-bold text-text mb-4">Your Information</h3>
              <div className="space-y-4">
                <Input
                  label="Full Name"
                  value={form.name}
                  onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
                  placeholder="Esther Nakamya"
                  required
                />
                <Input
                  label="Email Address"
                  type="email"
                  value={form.email}
                  onChange={e => setForm(f => ({ ...f, email: e.target.value }))}
                  placeholder="esther@example.com"
                  helperText="Download links will be sent to this email"
                  required
                />
                <Input
                  label="Phone (Optional)"
                  type="tel"
                  value={form.phone}
                  onChange={e => setForm(f => ({ ...f, phone: e.target.value }))}
                  placeholder="+256 700 000000"
                />
              </div>
            </div>
          </div>

          {/* Order summary + currency selector */}
          <div className="space-y-4">
            <div className="bg-white rounded-2xl p-6 border border-border">
              <h3 className="font-bold text-text mb-4">Order Summary</h3>

              {/* Line items */}
              <div className="space-y-3 mb-4">
                {items.map(item => (
                  <div key={item.product.id} className="flex justify-between text-sm">
                    <span className="text-text-muted line-clamp-1 flex-1 pr-2">{item.product.title}</span>
                    <span className="font-medium whitespace-nowrap">
                      {formatPrice(getProductPrice(item.product, selectedCurrency), selectedCurrency)}
                    </span>
                  </div>
                ))}
              </div>

              <div className="flex justify-between text-sm border-t border-border pt-3 mb-1">
                <span className="text-text-muted">Subtotal</span>
                <span className="font-medium">{formatPrice(subtotal, selectedCurrency)}</span>
              </div>
              {discount > 0 && (
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-text-muted">Discount</span>
                  <span className="text-green-600 font-medium">-{formatPrice(discount, selectedCurrency)}</span>
                </div>
              )}
              <div className="flex justify-between text-base font-bold border-t border-border pt-3 mt-2">
                <span>Total</span>
                <span>{formatPrice(total, selectedCurrency)}</span>
              </div>
            </div>

            {/* Currency selector */}
            <div className="bg-white rounded-2xl p-6 border border-border">
              <h3 className="font-bold text-text mb-1">Payment Currency</h3>
              <p className="text-xs text-text-muted mb-3">Select the currency you'd like to pay in</p>
              <div className="flex rounded-lg overflow-hidden border border-border">
                <button
                  onClick={() => setSelectedCurrency('UGX')}
                  className={`flex-1 py-3 text-sm font-semibold transition-colors ${selectedCurrency === 'UGX' ? 'bg-brand text-white' : 'bg-white text-text-muted hover:bg-surface-alt'}`}
                >
                  UGX (Ugandan Shilling)
                </button>
                <button
                  onClick={() => setSelectedCurrency('USD')}
                  className={`flex-1 py-3 text-sm font-semibold transition-colors ${selectedCurrency === 'USD' ? 'bg-brand text-white' : 'bg-white text-text-muted hover:bg-surface-alt'}`}
                >
                  USD (US Dollar)
                </button>
              </div>
              <p className="text-xs text-text-muted mt-2 text-center">
                You'll be charged: <span className="font-semibold text-text">{formatPrice(total, selectedCurrency)} {selectedCurrency}</span>
              </p>
            </div>

            {error && (
              <div className="bg-red-50 border border-red-200 rounded-xl p-4">
                <p className="text-sm text-red-600">{error}</p>
              </div>
            )}

            <Button
              variant="primary"
              className="w-full"
              onClick={handleCheckout}
              loading={loading}
            >
              <Lock className="w-4 h-4" />
              Pay {formatPrice(total, selectedCurrency)} via PesaPal
            </Button>

            <div className="flex items-center justify-center gap-2 text-xs text-text-muted">
              <Lock className="w-3 h-3" />
              <span>Secured by PesaPal - Instant digital delivery</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
