import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Lock, CreditCard } from 'lucide-react'
import { useCart } from '@/contexts/CartContext'
import { supabase } from '@/lib/supabase'
import { formatPrice } from '@/lib/utils'
import { getAuthToken, registerIPN, submitOrder } from '@/lib/pesapal'
import Button from '@/components/ui/Button'
import Input from '@/components/ui/Input'

export default function Checkout() {
  const navigate = useNavigate()
  const { items, total, discount, subtotal, currency, coupon, clearCart } = useCart()
  const [form, setForm] = useState({ name: '', email: '', phone: '' })
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  if (items.length === 0) {
    navigate('/cart')
    return null
  }

  async function handleCheckout() {
    if (!form.email || !form.name) {
      setError('Please fill in your name and email')
      return
    }
    setLoading(true)
    setError('')

    try {
      // 1. Create or get customer
      const { data: existingCustomer } = await supabase
        .from('bybisa_customers')
        .select('id')
        .eq('email', form.email.toLowerCase())
        .single()

      let customerId: string
      if (existingCustomer) {
        customerId = existingCustomer.id
      } else {
        const { data: newCustomer, error: custErr } = await supabase
          .from('bybisa_customers')
          .insert({ email: form.email.toLowerCase(), name: form.name, phone: form.phone || null })
          .select('id')
          .single()
        if (custErr) throw custErr
        customerId = newCustomer!.id
      }

      // 2. Create purchases for each item
      const purchases = []
      for (const item of items) {
        const { data: purchase, error: purchErr } = await supabase
          .from('bybisa_purchases')
          .insert({
            customer_id: customerId,
            product_id: item.product.id,
            order_number: '', // Auto-generated by trigger
            amount: item.product.price,
            currency: item.product.currency,
            status: 'pending',
          })
          .select('*')
          .single()
        if (purchErr) throw purchErr
        purchases.push(purchase!)
      }

      // 3. Track analytics
      for (const item of items) {
        await supabase.from('bybisa_analytics').insert({
          event_type: 'purchase',
          product_id: item.product.id,
          customer_id: customerId,
          metadata: { amount: item.product.price, currency: item.product.currency },
        })
      }

      // 4. Update coupon usage if applicable
      if (coupon) {
        await supabase
          .from('bybisa_coupons')
          .update({ uses_count: coupon.uses_count + 1 })
          .eq('id', coupon.id)
      }

      // 5. Initiate PesaPal payment
      try {
        const token = await getAuthToken()
        const ipnId = await registerIPN(token)
        const merchantRef = purchases[0].order_number
        
        const redirectUrl = await submitOrder(token, {
          id: merchantRef,
          currency: currency,
          amount: total,
          description: items.map(i => i.product.title).join(', '),
          callback_url: `${window.location.origin}/payment-callback?ref=${merchantRef}`,
          notification_id: ipnId,
          billing_address: {
            email_address: form.email,
            phone_number: form.phone || undefined,
            first_name: form.name.split(' ')[0],
            last_name: form.name.split(' ').slice(1).join(' ') || undefined,
          },
        })

        // Redirect to PesaPal
        window.location.href = redirectUrl
      } catch (payErr) {
        // If PesaPal fails, still save the orders as pending
        // and redirect to a success-pending page
        console.error('PesaPal error:', payErr)
        clearCart()
        navigate(`/payment-callback?ref=${purchases[0].order_number}&pending=true`)
      }
    } catch (err: any) {
      setError(err.message || 'An error occurred. Please try again.')
      setLoading(false)
    }
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <h1 className="font-heading text-3xl font-bold text-secondary mb-8">Checkout</h1>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Customer form */}
        <div className="space-y-6">
          <div className="bg-white rounded-xl border border-warm-border p-6">
            <h3 className="font-heading text-lg font-semibold text-secondary mb-4">Your Information</h3>
            <div className="space-y-4">
              <Input
                label="Full Name"
                id="name"
                value={form.name}
                onChange={e => setForm(f => ({ ...f, name: e.target.value }))}
                placeholder="Esther Nakamya"
                required
              />
              <Input
                label="Email Address"
                id="email"
                type="email"
                value={form.email}
                onChange={e => setForm(f => ({ ...f, email: e.target.value }))}
                placeholder="esther@example.com"
                helperText="Download links will be sent to this email"
                required
              />
              <Input
                label="Phone Number (Optional)"
                id="phone"
                type="tel"
                value={form.phone}
                onChange={e => setForm(f => ({ ...f, phone: e.target.value }))}
                placeholder="+256 700 000 000"
              />
            </div>
          </div>

          <div className="flex items-center gap-2 text-sm text-gray-500">
            <Lock className="w-4 h-4" />
            <span>Your payment is secured by PesaPal</span>
          </div>
        </div>

        {/* Order summary */}
        <div className="bg-white rounded-xl border border-warm-border p-6 h-fit sticky top-24">
          <h3 className="font-heading text-lg font-semibold text-secondary mb-4">Order Summary</h3>
          
          <div className="space-y-3 mb-4">
            {items.map(item => (
              <div key={item.product.id} className="flex justify-between text-sm">
                <span className="text-gray-600 line-clamp-2 flex-1 mr-2">{item.product.title}</span>
                <span className="font-medium whitespace-nowrap">{formatPrice(item.product.price, item.product.currency)}</span>
              </div>
            ))}
          </div>

          <div className="border-t border-warm-border pt-3 space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-gray-500">Subtotal</span>
              <span>{formatPrice(subtotal, currency)}</span>
            </div>
            {discount > 0 && (
              <div className="flex justify-between text-green-600">
                <span>Discount</span>
                <span>-{formatPrice(discount, currency)}</span>
              </div>
            )}
            <div className="flex justify-between text-base font-bold pt-2 border-t border-warm-border">
              <span>Total</span>
              <span>{formatPrice(total, currency)}</span>
            </div>
          </div>

          {error && (
            <div className="mt-4 p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600">
              {error}
            </div>
          )}

          <Button className="w-full mt-6" size="lg" loading={loading} onClick={handleCheckout}>
            <CreditCard className="w-5 h-5" />
            Pay {formatPrice(total, currency)}
          </Button>
        </div>
      </div>
    </div>
  )
}
